### ISSUE TITLE
`MPIPreferences` persists through pre-compilation cache.

### ISSUE THREAD

**Issue by t-bltg** [JuliaParallel/MPI.jl#646] opened 2022-09-28 22:30 UTC
As discussed with @giordano on slack, and I scratched my head a long time on this one:

```julia
julia> using MPIPreferences
julia> MPIPreferences.use_jll_binary("MPICH_jll")  # persistent `.toml` written
[...]

# restart julia
julia> using MPICH_jll, OpenMPI_jll  # precompiles
julia> MPICH_jll.is_available()
true
julia> MPIPreferences.use_jll_binary("OpenMPI_jll")  # I now decide to change the MPI implementation used
[...]

# restart julia
julia> using OpenMPI_jll  # does NOT precompile
julia> OpenMPI_jll.is_available()  # confusing since ~/.julia/environments/v1.8/LocalPreferences.toml states `binary = "OpenMPI_jll"`
false

# delete ~/.julia/compiled/OpenMPI_jll, restart julia
julia> using OpenMPI_jll  # precompiles
julia> OpenMPI_jll.is_available()
true
```

I believe `MPIPreferences` should invalidate the pre-compilation cache, or we should do something about `host_platform` being persistent in the precompilation cache.
I shouldn't have to delete `~/.julia/compiled/OpenMPI_jll` manually.

This leads to weird mix-ups such as:
```julia
julia> using MPICH_jll
julia> MPICH_jll.is_available()
false
julia> MPICH_jll.host_platform  # notice the mpi=openmpi :s
Linux x86_64 {cxxstring_abi=cxx11, julia_version=1.8.1, libc=glibc, libgfortran_version=5.0.0, libstdcxx_version=3.4.30, mpi=openmpi}
julia> using OpenMPI_jll
julia> OpenMPI_jll.is_available()
false
julia> OpenMPI_jll.host_platform  # notice the mpi=mpich :/
Linux x86_64 {cxxstring_abi=cxx11, julia_version=1.8.1, libc=glibc, libgfortran_version=5.0.0, libstdcxx_version=3.4.30, mpi=mpich}
```

Encountered in https://github.com/JuliaParallel/MPI.jl/pull/639#issuecomment-1261315777.

**Comment by simonbyrne** [comment] 2022-09-28 22:46
Is it because MPIPrefences isn't and explicit dependency of OpenMPI_jll?

CC @vchuravy

**Comment by simonbyrne** [comment] 2022-09-29 18:32
Is it because it isn't loaded?

**Comment by simonbyrne** [comment] 2022-09-29 18:39
Yes, changing that seems to fix it.

**Comment by simonbyrne** [comment] 2022-09-29 18:41
@giordano @vchuravy can we just load MPIPreferences directly from the platform augmentation code?

**Comment by simonbyrne** [comment] 2022-09-29 18:48
We can keep the discussion here, but the actual code that would need to be changed is here: https://github.com/JuliaPackaging/Yggdrasil/blob/cf634f846db9a448b747a7baaeafc6da5a874cf2/platforms/mpi.jl

**Comment by giordano** [comment] 2022-09-29 18:49
> Yes, changing that seems to fix it.

How did you change that?  The code comes from https://github.com/JuliaPackaging/Yggdrasil/blob/d247ec95b1e3b5d903a133fe185eb29485a1608b/platforms/mpi.jl (I also just noticed indentation is off)

**Comment by simonbyrne** [comment] 2022-09-29 18:50
I dev-ed OpenMPI_jll and modified it manually.

**Comment by simonbyrne** [comment] 2022-09-29 18:51
What does
```
# Can't use Preferences since we might be running this very early with a non-existing Manifest
```
refer to? When would this occur?

**Comment by giordano** [comment] 2022-09-29 18:52
> https://github.com/JuliaPackaging/Yggdrasil/blob/d247ec95b1e3b5d903a133fe185eb29485a1608b/platforms/mpi.jl#L6

Yes, but what's the change you did? https://github.com/JuliaPackaging/Yggdrasil/blob/d247ec95b1e3b5d903a133fe185eb29485a1608b/platforms/mpi.jl#L6 says we may be running without a Manifest

**Comment by simonbyrne** [comment] 2022-09-29 18:53
```patch
--- a/.pkg/platform_augmentation.jl
+++ b/.pkg/platform_augmentation.jl
@@ -1,4 +1,5 @@
     using Base.BinaryPlatforms
+    using MPIPreferences
         # Can't use Preferences since we might be running this very early with a non-existing Manifest
     MPIPreferences_UUID = Base.UUID("3da0fdf6-3ccc-4f1b-acd9-58baa6c99267")
     const preferences = Base.get_preferences(MPIPreferences_UUID)
```

**Comment by simonbyrne** [comment] 2022-09-29 18:54
I don't know what "running without a Manifest" means in this case. I can't test that as I need a Manifest to use a `dev`ed package.

**Comment by t-bltg** [comment] 2022-09-29 19:00
Maybe the following might cover `# Can't use Preferences since we might be running this very early with a non-existing Manifest`:
```julia
try
    using MPIPreferences
catch e
    @debug e
end
```

**Comment by simonbyrne** [comment] 2022-09-29 19:10
Not sure? I don't know the situation in which the code would be run without a Manifest.

**Comment by vchuravy** [comment] 2022-09-29 19:50
cc: @staticfloat 

The reason why we can't load it in the augmentation, is that it is run during `Pkg.add` and there the Manifes.toml is only partially installed.

**Comment by vchuravy** [comment] 2022-09-29 19:52
We should *not* be loadfing it during `platform_augmentation.jl`

The issue is that we load it in the generated wrapper files https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/blob/68a500cbd8a20f66b65acf0471c69bde0796b05e/src/wrappers/aarch64-apple-darwin-libgfortran5-mpi%2Bopenmpi.jl#L5 and not in the top-level file https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/blob/68a500cbd8a20f66b65acf0471c69bde0796b05e/src/OpenMPI_jll.jl#L7

**Comment by simonbyrne** [comment] 2022-09-29 20:03
> The reason why we can't load it in the augmentation, is that it is run during `Pkg.add` and there the Manifes.toml is only partially installed.

But it would have installed the dependencies already (including MPIPreferences)?

**Comment by vchuravy** [comment] 2022-09-29 20:13
`.pkg` is dark magic and is used in two distinct contexts. Once during the loading of the package itself and once during the installation of the package by Pkg. So the fact that adding MPIPreferences there fixed the issue is accidental. 

My proposed fix is that we move `using MPIPreferences` from the platform wrapper file to the top-level.

**Comment by simonbyrne** [comment] 2022-09-29 20:25
Out of curiousity, why does it need to be loaded during package loading? where is the code that handles this?

**Comment by vchuravy** [comment] 2022-09-29 21:23
> where is the code that handles this?

https://cs.github.com/JuliaLang/Pkg.jl/blob/de13dafeab58b59c6c933b4836e58303862cfd2d/src/Operations.jl#L622 and then https://github.com/JuliaBinaryWrappers/OpenMPI_jll.jl/blob/a4b7bf25afd5e5c134e8e4f9117d47c2cdf12ac2/.pkg/select_artifacts.jl#L4

**Comment by vchuravy** [comment] 2022-10-03 14:25
Should be fixed by:
- https://github.com/JuliaPackaging/Yggdrasil/pull/5616
- https://github.com/JuliaPackaging/Yggdrasil/pull/5617
- https://github.com/JuliaPackaging/Yggdrasil/pull/5618

**Comment by simonbyrne** [comment] 2022-10-03 16:15
Can confirm it is now fixed.

**Closed by simonbyrne** 2022-10-03 16:15 UTC
