### ISSUE TITLE
Installed MPI.jl doesn't pass the test "test_shared_win.jl".

### ISSUE THREAD

**Issue by liuspace** [JuliaParallel/MPI.jl#347] opened 2020-02-14 22:29 UTC
MPI.jl is installed. Most test cases are passed except the test_shared_win.jl. I am using Julia 1.0 and MPICH (Version 3.3b1) on Mac. 

**The issue is listed as follows.** Please give me some suggestions what is wrong there.
```
signal (11): Segmentation fault: 11
in expression starting at ~/.julia/packages/MPI/G4WHR/test/test_shared_win.jl:60
copyto! at ./array.jl:769
copyto! at ./abstractarray.jl:723 [inlined]
copyto! at ./broadcast.jl:841 [inlined]
copyto! at ./broadcast.jl:800 [inlined]
materialize! at ./broadcast.jl:759 [inlined]
main at ~/.julia/packages/MPI/G4WHR/test/test_shared_win.jl:39
unknown function (ip: 0x10860bd61) 
jl_fptr_trampoline at /Users/julia/buildbot/worker/package_macos64/build/src/gf.c:1809
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:324
eval_stmt_value at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:697
jl_interpret_toplevel_thunk_callback at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:806
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x10674800f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:815
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:805
jl_parse_eval_all at /Users/julia/buildbot/worker/package_macos64/build/src/ast.c:838
jl_load at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:839 [inlined]
jl_load_ at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:846
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1044
include at ./sysimg.jl:29
exec_options at ./client.jl:266
_start at ./client.jl:425
true_main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-1.0.app/Contents/Resources/julia/bin/julia (unknown line)
Allocations: 3919615 (Pool: 3918735; Big: 880); GC: 8

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 24842 RUNNING AT pn1715089.lanl.gov
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault: 11 (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by simonbyrne** [comment] 2020-02-14 22:59
What version of MPI.jl are you using? You can find out by 
```
julia --project -e 'using Pkg; Pkg.status()'
```

**Comment by simonbyrne** [comment] 2020-02-14 23:03
Also, is there any reason you are using an old preview release of MPICH? Can you try it with a newer stable version?

**Comment by liuspace** [comment] 2020-02-14 23:03
> What version of MPI.jl are you using? You can find out by
> ```
> julia --project -e 'using Pkg; Pkg.status()'
> ```
  Thanks, Simon. I am using the following version.

  [da04e1cc] MPI v0.11.0 #master (https://github.com/JuliaParallel/MPI.jl)

**Comment by liuspace** [comment] 2020-02-14 23:08
> Also, is there any reason you are using an old preview release of MPICH? Can you try it with a newer stable version?

I need to add package MPI.jl and Pets2.jl. Right now, Petsc2.jl only support Petsc 3.9.6 (the accompanying MPICH is version 3.3.b) and Julia 0.6. In order to make it easier to code wrapper file for Petsc in future,
I selected this version for Petsc and the accompanying MPICH.

**Comment by simonbyrne** [comment] 2020-02-14 23:15
Ah ok.  I would suggest trying it with a newer MPICH version to at least see if you can determine the cause. I don't have any experience with that part of the code, so it is difficult to say what is going on. @barche do you have any ideas?

Unless your package is using the shared memory functionality, it is probably safe to ignore.

**Comment by liuspace** [comment] 2020-02-14 23:18
> Ah ok. I would suggest trying it with a newer MPICH version to at least see if you can determine the cause. I don't have any experience with that part of the code, so it is difficult to say what is going on. @barche do you have any ideas?
> 
> Unless your package is using the shared memory functionality, it is probably safe to ignore.


Sure. I will try new MPICH.

**Comment by liuspace** [comment] 2020-02-15 00:49
> Also, is there any reason you are using an old preview release of MPICH? Can you try it with a newer stable version?

    I tried newer MPICH (3.3.2) and it works well now. Weird. 
    All the tests have been validated. 
    Thanks,

**Comment by simonbyrne** [comment] 2020-02-18 17:45
Great, I'll close this then. Please open a new issue if further problems arise.

**Closed by simonbyrne** 2020-02-18 17:45 UTC
