### ISSUE TITLE
Trouble using MPI on Julia v1.7 and on a MacBook Pro M1

### ISSUE THREAD

**Issue by navidcy** [JuliaParallel/MPI.jl#583] opened 2022-04-28 00:42 UTC
I have trouble using MPI on Julia v1.7 and on a MacBook Pro M1 (ARM). Have a look below:

```Julia
(base) navid:test_Oceananigans/ $ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.2 (2022-02-06)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_EDITOR = code

(@v1.7) pkg> activate .
  Activating project at `~/Research/test_Oceananigans`

(test_Oceananigans) pkg> add MPI
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
    Updating `~/Research/test_Oceananigans/Project.toml`
  [da04e1cc] + MPI v0.19.2
    Updating `~/Research/test_Oceananigans/Manifest.toml`
  [ffbed154] + DocStringExtensions v0.8.6
  [692b3bcd] + JLLWrappers v1.4.1
  [da04e1cc] + MPI v0.19.2
  [21216c6a] + Preferences v1.3.0
  [ae029012] + Requires v1.3.0
  [7cb0a576] + MPICH_jll v4.0.2+0
  [9237b28f] + MicrosoftMPI_jll v10.1.3+2
  [fe0851c0] + OpenMPI_jll v4.1.2+0
  [0dad84c5] + ArgTools
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [f43a241f] + Downloads
  [b77e0a4c] + InteractiveUtils
  [4af54fe1] + LazyArtifacts
  [b27032c2] + LibCURL
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [fa267f1f] + TOML
  [a4e569a6] + Tar
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll
  [deac9b47] + LibCURL_jll
  [29816b5a] + LibSSH2_jll
  [c8ffd9c3] + MbedTLS_jll
  [14a3606d] + MozillaCACerts_jll
  [83775a58] + Zlib_jll
  [8e850ede] + nghttp2_jll
  [3f19e933] + p7zip_jll

(test_Oceananigans) pkg> build MPI
    Building MPI → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/d56a80d8cf8b9dc3050116346b3d83432b1912c0/build.log`

julia> using MPI
ERROR: InitError: could not load library "/Users/navid/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/libmpifort.12.dylib"
dlopen(/Users/navid/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/libmpifort.12.dylib, 0x0001): Library not loaded: @rpath/libquadmath.0.dylib
  Referenced from: /Users/navid/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/libmpifort.12.dylib
  Reason: tried: '/Users/navid/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/./libquadmath.0.dylib' (no such file), '/Users/navid/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/./libquadmath.0.dylib' (no such file), '/Users/navid/julia-1.7/usr/lib/libquadmath.0.dylib' (no such file), '/Users/navid/julia-1.7/usr/bin/../lib/libquadmath.0.dylib' (no such file), '/usr/local/lib/libquadmath.0.dylib' (no such file), '/usr/lib/libquadmath.0.dylib' (no such file)
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:117
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
  [4] __init__()
    @ MPICH_jll ~/.julia/packages/MPICH_jll/dhUyI/src/wrappers/aarch64-apple-darwin-libgfortran5.jl:32
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
  [7] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:783
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:843
  [9] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
 [10] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
 [11] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
during initialization of module MPICH_jll
```

**Comment by glwagner** [comment] 2022-04-28 00:53
Might be a problem with `MPICH_jll` version 4.0.2 because pinning at 4.0.1 seems to solve it.

```julia
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.2 (2022-02-06)
 _/ |\__'_|_|_|\__'_|  |  HEAD/bf53498635 (fork: 461 commits, 322 days)
|__/                   |

(@v1.7) pkg> activate .
  Activating new project at `~/Desktop/test`

(test) pkg> add MPI

julia> using MPI
ERROR: InitError: could not load library "/Users/gregorywagner/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/libmpifort.12.dylib"
dlopen(/Users/gregorywagner/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/libmpifort.12.dylib, 0x0001): Library not loaded: @rpath/libquadmath.0.dylib
  Referenced from: /Users/gregorywagner/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/libmpifort.12.dylib
  Reason: tried: '/Users/gregorywagner/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/./libquadmath.0.dylib' (no such file), '/Users/gregorywagner/.julia/artifacts/48a9a608db31268626d8b8d4d1272c3e7ccbf7d5/lib/./libquadmath.0.dylib' (no such file), '/Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libquadmath.0.dylib' (no such file), '/Applications/Julia-1.7.app/Contents/Resources/julia/bin/../lib/libquadmath.0.dylib' (no such file), '/usr/local/lib/libquadmath.0.dylib' (no such file), '/usr/lib/libquadmath.0.dylib' (no such file)
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:117
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
  [4] __init__()
    @ MPICH_jll ~/.julia/packages/MPICH_jll/dhUyI/src/wrappers/aarch64-apple-darwin-libgfortran5.jl:32
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
  [7] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:783
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:843
  [9] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
 [10] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
 [11] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
during initialization of module MPICH_jll

(test) pkg> add MPICH_jll@v4.0.1
   Resolving package versions...
    Updating `~/Desktop/test/Project.toml`
  [7cb0a576] + MPICH_jll v4.0.1+0
    Updating `~/Desktop/test/Manifest.toml`
  [7cb0a576] ↓ MPICH_jll v4.0.2+0 ⇒ v4.0.1+0

(test) pkg> build
    Building MPI → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/d56a80d8cf8b9dc3050116346b3d83432b1912c0/build.log`

julia>
gregorywagner:test/ $ julia17 --project                                                                  [20:49:46]
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.2 (2022-02-06)
 _/ |\__'_|_|_|\__'_|  |  HEAD/bf53498635 (fork: 461 commits, 322 days)
|__/                   |

julia> using MPI

julia>
```

**Comment by vchuravy** [comment] 2022-04-28 01:12
Duplicate of https://github.com/JuliaParallel/MPI.jl/issues/567#issuecomment-1100870486

**Comment by glwagner** [comment] 2022-04-28 01:36
Thanks @vchuravy. We'll pin to 4.0.1 until we're basking in the bright light of Julia 1.8

**Closed** 2022-04-28 01:56 UTC
