### ISSUE TITLE
Problem precompiling MPIPreferences and SnoopCompile

### ISSUE THREAD

**Issue by lcw** [JuliaParallel/MPI.jl#729] opened 2023-04-26 21:39 UTC
Trying to load MPIPreferences and SnoopCompile into the same environment
leads to problems precompiling (see the output below).

```
❯ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.0-rc2 (2023-04-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.9) pkg> activate --temp
  Activating new project at `/tmp/jl_HaFDFt`

(jl_HaFDFt) pkg> add MPIPreferences SnoopCompile
   Resolving package versions...
    Updating `/tmp/jl_HaFDFt/Project.toml`
  [3da0fdf6] + MPIPreferences v0.1.7
  [aa65fe97] + SnoopCompile v2.10.6
    Updating `/tmp/jl_HaFDFt/Manifest.toml`
  [1520ce14] + AbstractTrees v0.4.4
  [da1fd8a2] + CodeTracking v1.3.1
  [3da002f7] + ColorTypes v0.11.4
  [5ae59095] + Colors v0.12.10
  [f68482b8] + Cthulhu v2.8.14
  [5789e2e9] + FileIO v1.16.0
  [53c48c17] + FixedPointNumbers v0.8.4
  [08572546] + FlameGraphs v1.0.0
  [1eca21be] + FoldingTrees v1.2.1
  [9b13fd28] + IndirectArrays v1.0.0
  [c3a54625] + JET v0.7.12
  [692b3bcd] + JLLWrappers v1.4.1
  [aa1ae85d] + JuliaInterpreter v0.9.23
  [70703baa] + JuliaSyntax v0.3.4
  [1d6d02ad] + LeftChildRightSiblingTrees v0.2.0
  [6f1432cf] + LoweredCodeUtils v2.3.0
  [3da0fdf6] + MPIPreferences v0.1.7
  [1914dd2f] + MacroTools v0.5.10
  [bac558e1] + OrderedCollections v1.6.0
  [aea7be01] + PrecompileTools v1.0.1
  [21216c6a] + Preferences v1.3.0
  [189a3867] + Reexport v1.2.2
  [ae029012] + Requires v1.3.0
  [295af30f] + Revise v3.5.2
  [aa65fe97] + SnoopCompile v2.10.6
  [e2b509da] + SnoopCompileCore v2.10.0
  [69024149] + StringEncodings v0.3.6
  [d265eb64] + TypedSyntax v1.1.9
  [b8c1c048] + WidthLimitedIO v1.0.1
  [ddb6d928] + YAML v0.4.8
  [94ce4f54] + Libiconv_jll v1.16.1+2
  [0dad84c5] + ArgTools v1.1.1
  [56f22d72] + Artifacts
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [f43a241f] + Downloads v1.6.0
  [7b1f6079] + FileWatching
  [b77e0a4c] + InteractiveUtils
  [b27032c2] + LibCURL v0.6.3
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [ca575930] + NetworkOptions v1.2.0
  [44cfe95a] + Pkg v1.9.0
  [de0858da] + Printf
  [9abbd945] + Profile
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics v1.9.0
  [fa267f1f] + TOML v1.0.3
  [a4e569a6] + Tar v1.10.0
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
  [e66e0078] + CompilerSupportLibraries_jll v1.0.2+0
  [deac9b47] + LibCURL_jll v7.84.0+0
  [29816b5a] + LibSSH2_jll v1.10.2+0
  [c8ffd9c3] + MbedTLS_jll v2.28.2+0
  [14a3606d] + MozillaCACerts_jll v2022.10.11
  [4536629a] + OpenBLAS_jll v0.3.21+4
  [bea87d4a] + SuiteSparse_jll v5.10.1+6
  [83775a58] + Zlib_jll v1.2.13+0
  [8e850b90] + libblastrampoline_jll v5.4.0+0
  [8e850ede] + nghttp2_jll v1.48.0+0
  [3f19e933] + p7zip_jll v17.4.0+0
Precompiling environment...
  ✗ SnoopCompile
  0 dependencies successfully precompiled in 2 seconds. 35 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

(jl_HaFDFt) pkg> precompile
Precompiling environment...
  ✗ SnoopCompile
  0 dependencies successfully precompiled in 1 seconds. 35 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

SnoopCompile [aa65fe97-06da-5843-b5b1-d5d13cad87d2]

Failed to precompile SnoopCompile [aa65fe97-06da-5843-b5b1-d5d13cad87d2] to "/home/lucas/.julia/compiled/v1.9/SnoopCompile/jl_kKmhKt".
ERROR: LoadError: InitError: Evaluation into the closed module `Preferences` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Preferences` with `eval` during precompilation - don't do this.
Stacktrace:
  [1] eval
    @ ./boot.jl:370 [inlined]
  [2] (::JET.var"#77#78")()
    @ JET ~/.julia/packages/JET/X3otm/src/toplevel/virtualprocess.jl:1371
  [3] (::JET.var"#2#3")(f::Any)
    @ JET ~/.julia/packages/JET/X3otm/src/JET.jl:134
  [4] foreach
    @ ./abstractarray.jl:3073 [inlined]
  [5] __init__()
    @ JET ~/.julia/packages/JET/X3otm/src/JET.jl:134
  [6] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1074
  [7] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:1020
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base ./loading.jl:1469
  [9] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1750
 [10] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1623
 [11] macro expansion
    @ ./loading.jl:1611 [inlined]
 [12] macro expansion
    @ ./lock.jl:267 [inlined]
 [13] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1574
 [14] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [15] include(x::String)
    @ SnoopCompile ~/.julia/packages/SnoopCompile/bjS5I/src/SnoopCompile.jl:46
 [16] top-level scope
    @ ~/.julia/packages/SnoopCompile/bjS5I/src/SnoopCompile.jl:97
 [17] include
    @ ./Base.jl:457 [inlined]
 [18] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2012
 [19] top-level scope
    @ stdin:2
during initialization of module JET
in expression starting at /home/lucas/.julia/packages/SnoopCompile/bjS5I/src/parcel_snoopi_deep.jl:10
in expression starting at /home/lucas/.julia/packages/SnoopCompile/bjS5I/src/SnoopCompile.jl:1
in expression starting at stdin:2
```

**Comment by vchuravy** [comment] 2023-04-26 22:15
cc: @timholy

**Comment by sloede** [comment] 2023-04-27 03:39
We’re also starting to see this issue pop up in CI runs, e.g., [here](https://github.com/trixi-framework/Trixi.jl/actions/runs/4811203788/jobs/8564878793?pr=1399).

**Comment by simonbyrne** [comment] 2023-04-27 04:24
Top line in stack trace is this:
https://github.com/aviatesk/JET.jl/blob/b61b39b10c36f82999ee9842eda4437686701ad0/src/toplevel/virtualprocess.jl#L1371

**Comment by aviatesk** [comment] 2023-04-27 06:08
This should be fixed now as JET@0.7.13 has been released.

**Comment by sloede** [comment] 2023-04-27 06:15
At least for our CI, the issue is gone.

**Comment by lcw** [comment] 2023-04-27 16:22
Works for me now.  Thanks for the quick fix!

**Closed** 2023-04-27 16:22 UTC
